version: '3.9'

networks:
    network:

services:
    php:
        build:
            args:
                user: bojan
                group: bojan
            context: ./docker/php
            dockerfile: Dockerfile
        volumes:
            - ./:/var/www/html
        ports:
            - "9000:9000"
            - "3000:3000"
        networks:
            - network

    mysql:
        image: mariadb:10.8.3
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        networks:
            - network

    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php
            - mysql
        networks:
            - network

    adminer:
        image: adminer
        ports:
            - "8080:8080"
        networks:
            - network

    mailhog:
        image: mailhog/mailhog
        ports:
            - "1025:1025"
            - "8025:8025"
        networks:
            - network
